name: Publish Docker

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    name: Build Docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Docker Package Registry
        uses: craftech-io/package-action@v3.1.0
        with:
          access_token: ${{ secrets.GITHUB_TOKEN }}
          context: src
          tags: |
            latest
            ${{ github.sha }}
